version: "3.9"

services:
  # -------------------------------------
  # MongoDB Database
  # -------------------------------------
  mongodb:
    image: mongo:7.0
    container_name: lms-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lms
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - lms-network
    restart: always

  # -------------------------------------
  # Backend (Node.js)
  # -------------------------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/lms?authSource=admin
      JWT_SECRET: your-jwt-secret-key
      CLOUDINARY_CLOUD_NAME: your-cloudinary-cloud-name
      CLOUDINARY_API_KEY: your-cloudinary-api-key
      CLOUDINARY_API_SECRET: your-cloudinary-api-secret
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      ML_SERVICE_URL: http://ml-service:8000
    depends_on:
      - mongodb
      - ml-service
    networks:
      - lms-network
    restart: always

  # -------------------------------------
  # Frontend (React + Vite)
  # -------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lms-frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - lms-network
    restart: always

  # -------------------------------------
  # ML Plagiarism Service (FastAPI)
  # -------------------------------------
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: lms-ml-service
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
    networks:
      - lms-network
    restart: always

# -------------------------------------
# Volumes
# -------------------------------------
volumes:
  mongodb_data:
    driver: local

# -------------------------------------
# Networks
# -------------------------------------
networks:
  lms-network:
    driver: bridge
